FROM node:22-alpine AS base
  # https://nextjs.org/telemetry
  ENV NEXT_TELEMETRY_DISABLED=1
  # https://turbo.build/repo/docs/telemetry
  ENV TURBO_TELEMETRY_DISABLED=1
  # Set Sharp to use prebuilt binaries
  ENV SHARP_IGNORE_GLOBAL_LIBVIPS=1

FROM base AS basewithtools
  ENV PNPM_HOME="/pnpm"
  ENV PATH="$PNPM_HOME:$PATH"
  RUN apk add --no-cache libc6-compat && \
    npm install -g pnpm@9.15.1 turbo@2.3.3