name: Docker Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        run: echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Docker images
        run: |
          docker build -t ghcr.io/${{ env.REPO_LOWERCASE }}:latest .
          docker build -f Dockerfile-alpine --target base -t ghcr.io/${{ env.REPO_LOWERCASE }}:alpine .
          docker build -f Dockerfile-alpine --target basewithtools -t ghcr.io/${{ env.REPO_LOWERCASE }}:alpinewithtool .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ env.REPO_LOWERCASE }}:latest
          docker push ghcr.io/${{ env.REPO_LOWERCASE }}:alpine
          docker push ghcr.io/${{ env.REPO_LOWERCASE }}:alpinewithtool
